name: Compilay Genera PDF

on:
  push:

jobs:
  compila:
    runs-on: ubuntu-latest

    steps:
    - name: Saludar (custom action)
      uses: ricnef2121/custom-github-action@v1.1 ## name's repo
      with:
        who-to-greet: "Ricardo"
    - name: Tener copi local del repo
      uses: actions/checkout@4.2.2
    - name: Instalar .Net en el runner
      uses: actions/setup-dotnet@v3.4.2
      with:
        dotnet-version: '9.0.x'
    - name: Instalar dependencias
      run: dotnet restore
    - name: Compilar
      run: dotnet build --no-restore
  crear-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
          
      
